version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0

workflows:
  run-tests:
    jobs:
      - rspec: # <-- this is a job using the captain CLI
          context: rwx # <-- this is the context that contains the `RWX_ACCESS_TOKEN` environment variable
      - rspec-with-retries:
          context: rwx
      - rspec-with-partitioning:
          context: rwx
      - rspec-with-partitioning-retries:
          context: rwx

jobs:
  rspec:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Download Captain
          command: |
            arch=x86_64  # Supported values are x86_64 or aarch64
            os=linux     # Supported values are linux or darwin

            tmp="$(mktemp -d)/captain" && \
              curl -o $tmp -fsSL "https://releases.captain.build/v1/$os/$arch/captain" && \
              sudo install $tmp /usr/local/bin && \
              rm $tmp && \
              captain --version
      - run:
          name: run tests
          command: captain run captain-examples-rspec
      - store_test_results:
          path: tmp/junit.xml

  rspec-with-retries:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Download Captain
          command: |
            arch=x86_64  # Supported values are x86_64 or aarch64
            os=linux # Supported values are linux or darwin

            tmp="$(mktemp -d)/captain" && \
              curl -o $tmp -fsSL "https://releases.captain.build/v1/$os/$arch/captain" && \
              sudo install $tmp /usr/local/bin && \
              rm $tmp && \
              captain --version
      - run:
          name: run tests with retries
          command: captain run captain-examples-rspec-retries
      - store_test_results:
          path: tmp/junit.xml

  rspec-with-partitioning:
    parallelism: 2
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Download Captain
          command: |
            arch=x86_64  # Supported values are x86_64 or aarch64
            os=linux # Supported values are linux or darwin

            tmp="$(mktemp -d)/captain" && \
              curl -o $tmp -fsSL "https://releases.captain.build/v1/$os/$arch/captain" && \
              sudo install $tmp /usr/local/bin && \
              rm $tmp && \
              captain --version
      - run:
          name: run tests with partitioning
          command: |
            export CAPTAIN_SUITE_ID="captain-examples-rspec"

            test_files=$(
              captain partition \
              --index $CIRCLE_NODE_INDEX \
              --total $CIRCLE_NODE_TOTAL \
              "spec/**/*_spec.rb"
            )

            captain run -c "bundle exec rspec --format json --out tmp/rspec.json --format progress $test_files"
      - store_test_results:
          path: tmp/junit.xml

  rspec-with-partitioning-retries:
    parallelism: 2
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Download Captain
          command: |
            arch=x86_64  # Supported values are x86_64 or aarch64
            os=linux # Supported values are linux or darwin

            tmp="$(mktemp -d)/captain" && \
              curl -o $tmp -fsSL "https://releases.captain.build/v1/$os/$arch/captain" && \
              sudo install $tmp /usr/local/bin && \
              rm $tmp && \
              captain --version
      - run:
          name: run tests with partitioning and retries
          command: |
            export CAPTAIN_SUITE_ID="captain-examples-rspec-retries"

            test_files=$(
              captain partition \
              --index $CIRCLE_NODE_INDEX \
              --total $CIRCLE_NODE_TOTAL \
              "spec/**/*_spec.rb"
            )

            captain run -c "bundle exec rspec --format json --out tmp/rspec.json --format progress $test_files"

      - store_test_results:
          path: tmp/junit.xml
