version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0

workflows:
  run-rspec-with-captain:
    jobs:
      - rspec-with-captain:
          context: rwx


jobs:
  rspec-with-captain:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Download Captain
          command: |
            arch=x86_64  # Supported values are x86_64 or aarch64
            os=linux # Supported values are linux or darwin

            tmp="$(mktemp -d)/captain" && \
              curl -o $tmp -fsSL "https://releases.captain.build/v1/$os/$arch/captain" && \
              sudo install $tmp /usr/local/bin && \
              rm $tmp && \
              captain --version
      - run:
          name: run tests with captain
          command: |
            captain run \
              --suite-id captain-examples-circle-rspec \
              --test-results tmp/rspec.json \
              -- \
              bundle exec rspec \
                --format json --out tmp/rspec.json \
                --format progress
